# Generated by Django 6.0.6 on 2026-09-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='cate_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='cate_nombre', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, db_column='cate_descripcion', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='prod_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='prod_nombre', max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, db_column='prod_descripcion', verbose_name='Descripción')),
                ('price', models.DecimalField(db_column='prod_precio', decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(db_column='prod_stock', default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, db_column='prod_imagen', null=True, upload_to='products/', verbose_name='Imagen')),
                ('qr_code', models.ImageField(blank=True, db_column='prod_qr', editable=False, upload_to='qrcodes/', verbose_name='Código QR')),
                ('active', models.BooleanField(db_column='prod_activo', default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='prod_creado', verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='prod_actualizado', verbose_name='Actualizado el')),
                ('category', models.ForeignKey(blank=True, db_column='prod_categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
