# Generated by Django 6.0.6 on 2026-06-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, upload_to='qrcodes/'),
        ),
    ]
