# Generated by Django 6.0.6 on 2026-09-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(db_column='vent_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='vent_fecha', verbose_name='Fecha')),
                ('total', models.DecimalField(db_column='vent_total', decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('client_name', models.CharField(blank=True, db_column='vent_cliente', max_length=200, verbose_name='Cliente')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], db_column='vent_metodo_pago', default='cash', max_length=10, verbose_name='Método de pago')),
                ('cancelled', models.BooleanField(db_column='vent_anulada', default=False, verbose_name='Anulada')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(db_column='deta_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='deta_cantidad', verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(db_column='deta_precio_unitario', decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('discount', models.DecimalField(db_column='deta_descuento', decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(db_column='deta_subtotal', decimal_places=2, max_digits=12, verbose_name='Subtotal')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'detalle_venta',
            },
        ),
    ]
