# Generated by Django 6.0.6 on 2026-09-11 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(db_column='vent_vendedor_id', limit_choices_to={'role__in': ['seller', 'admin']}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(db_column='deta_producto_id', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(db_column='deta_venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='Venta'),
        ),
    ]
