# Generated by Django 6.0.6 on 2026-06-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
