# Generated by Django 6.0.6 on 2026-09-11 06:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(db_column='usua_usuario', max_length=150, unique=True, verbose_name='Usuario')),
                ('first_name', models.CharField(blank=True, db_column='usua_nombre', max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, db_column='usua_apellido', max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, db_column='usua_correo', max_length=254, verbose_name='Correo')),
                ('password', models.CharField(db_column='usua_contrasena', max_length=128, verbose_name='Contraseña')),
                ('is_superuser', models.BooleanField(db_column='usua_es_superusuario', default=False, verbose_name='Es superusuario')),
                ('is_staff', models.BooleanField(db_column='usua_es_staff', default=False, verbose_name='Es staff')),
                ('is_active', models.BooleanField(db_column='usua_esta_activo', default=True, verbose_name='Está activo')),
                ('last_login', models.DateTimeField(blank=True, db_column='usua_ultimo_acceso', null=True, verbose_name='Último acceso')),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='usua_fecha_ingreso', verbose_name='Fecha de ingreso')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('owner', 'Propietario'), ('seller', 'Vendedor')], db_column='usua_rol', default='seller', max_length=10, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, db_column='usua_telefono', max_length=20, verbose_name='Teléfono')),
                ('id', models.BigAutoField(db_column='usua_id', primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
